-- ===========================================================================
-- AUDIT 1 — ITEM 2: budget_items transactional sync RPC + idempotency key
-- ===========================================================================
-- Closes the partial-failure / non-transactionality documented in
-- AUDIT1-ITEM2-DIAGNOSIS.md §5. The PostgREST chain at
-- src/app/api/budgets/update/route.ts:312-514 is replaced by a single
-- SECURITY DEFINER RPC that wraps snapshot → DELETE → INSERT → UPDATE →
-- budget_versions.total_amount_kes recompute → audit_logs summary INSERT
-- in one Postgres transaction.
--
-- Scope lock (AUDIT1-ITEM2-DIAGNOSIS.md "Answers from Njuguna"):
--   A1 — DELETE → INSERT → UPDATE (id sets are disjoint at the route layer,
--        see AUDIT1-ITEM2-DESIGN.md §7 Q0).
--   A2 — Audit-write failure aborts the whole transaction.
--   A3 — Keep both audit rails (per-row trigger + explicit summary).
--   A4 — Accept NULL user_id on per-row trigger rows for now.
--   A5 — Wrap the full 5-step chain inside the RPC.
--   A6 — Idempotency: nullable UUID column + partial unique index.
--   A7 — Parent-field path stays a separate call (out of scope).
--
-- Phase 3a (this migration): install the column, index, and function.
-- Phase 3b (separate commit): change route.ts to call the RPC. Until
-- Phase 3b ships, the application continues to run the existing
-- non-transactional chain; the RPC is dormant. This staged rollout
-- means the migration can be applied independently of any code change.
--
-- Apply: paste into Supabase Dashboard → SQL Editor.
--
-- Drift caveat (per AGENTS.md): verify the live `budget_items` table does
-- not already carry an `idempotency_key` column from prior ad-hoc work.
-- The IF NOT EXISTS guards below tolerate a pre-existing column of the
-- same type; a different-typed pre-existing column would surface as a
-- separate error.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Idempotency column
-- ---------------------------------------------------------------------------
-- Pattern matches 00047_payments_idempotency_key.sql:30-31. Nullable so
-- historical rows are not affected (legacy rows stay NULL); the partial
-- unique index below enforces uniqueness only when the key is set.
-- No backfill — pre-existing rows remain NULL by design.

ALTER TABLE public.budget_items
  ADD COLUMN IF NOT EXISTS idempotency_key UUID NULL;


-- ---------------------------------------------------------------------------
-- 2. Partial unique index
-- ---------------------------------------------------------------------------
-- Name follows the 00047 precedent (`idx_<table>_idempotency_key`). Partial
-- so legacy NULL rows are not constrained; a second INSERT carrying the
-- same key fails at this index with SQLSTATE 23505 (unique_violation).
-- fn_budget_items_sync probes for an existing key before any INSERT, so
-- the index is the defence-in-depth backstop rather than the primary
-- guard.

CREATE UNIQUE INDEX IF NOT EXISTS idx_budget_items_idempotency_key
  ON public.budget_items (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

COMMENT ON COLUMN public.budget_items.idempotency_key IS
  'Per-save UUID generated by the route layer (or relayed from the client) and stamped on every row inserted by fn_budget_items_sync. Prevents duplicate sync chains: a retried RPC short-circuits when any existing row carries the same key. NULL allowed for legacy rows recorded before this column existed.';


-- ---------------------------------------------------------------------------
-- 3. fn_budget_items_sync
-- ---------------------------------------------------------------------------
-- See AUDIT1-ITEM2-DESIGN.md §1 for the full annotated rationale.

CREATE OR REPLACE FUNCTION public.fn_budget_items_sync(
  p_version_id       UUID,
  p_user_id          UUID,
  p_added            JSONB,
  p_edited           JSONB,
  p_deleted          UUID[],
  p_idempotency_key  UUID
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_existing_total NUMERIC;
  v_before_snapshot JSONB;
  v_added_rows JSONB;
  v_edited_rows JSONB;
  v_deleted_rows JSONB;
  v_new_total NUMERIC;
  v_audit_id UUID;
  v_added_count INT;
  v_edited_count INT;
  v_deleted_count INT;
  v_touched_ids UUID[];
BEGIN
  IF p_idempotency_key IS NULL THEN
    RAISE EXCEPTION 'p_idempotency_key is required'
      USING ERRCODE = 'P0001', HINT = 'route layer must generate one per save';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.budget_items
     WHERE idempotency_key = p_idempotency_key
  ) THEN
    SELECT total_amount_kes INTO v_existing_total
      FROM public.budget_versions
     WHERE id = p_version_id;

    RETURN jsonb_build_object(
      'ok',                TRUE,
      'idempotent_hit',    TRUE,
      'version_total_kes', COALESCE(v_existing_total, 0),
      'audit_log_id',      NULL
    );
  END IF;

  PERFORM 1 FROM public.budget_versions WHERE id = p_version_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'budget version % not found', p_version_id
      USING ERRCODE = 'P0001';
  END IF;

  v_added_count   := COALESCE(jsonb_array_length(p_added),  0);
  v_edited_count  := COALESCE(jsonb_array_length(p_edited), 0);
  v_deleted_count := COALESCE(array_length(p_deleted, 1),   0);

  v_touched_ids := COALESCE(p_deleted, ARRAY[]::UUID[])
                || COALESCE(
                     ARRAY(SELECT (e->>'id')::UUID
                             FROM jsonb_array_elements(p_edited) e),
                     ARRAY[]::UUID[]
                   );

  IF v_touched_ids IS NOT NULL AND array_length(v_touched_ids, 1) > 0 THEN
    IF EXISTS (
      SELECT 1
        FROM unnest(v_touched_ids) AS t(id)
       WHERE NOT EXISTS (
         SELECT 1 FROM public.budget_items bi
          WHERE bi.id = t.id
            AND bi.budget_version_id = p_version_id
       )
    ) THEN
      RAISE EXCEPTION 'one or more line items do not belong to version %', p_version_id
        USING ERRCODE = 'P0001', HINT = 'ITEMS_NOT_FOUND';
    END IF;
  END IF;

  SELECT COALESCE(
    jsonb_agg(jsonb_build_object(
      'id',          bi.id,
      'description', bi.description,
      'category',    bi.category,
      'amount_kes',  bi.amount_kes,
      'sort_order',  bi.sort_order
    )),
    '[]'::jsonb
  )
    INTO v_before_snapshot
    FROM public.budget_items bi
   WHERE bi.budget_version_id = p_version_id
     AND bi.id = ANY (v_touched_ids);

  IF v_deleted_count > 0 THEN
    WITH del AS (
      DELETE FROM public.budget_items
       WHERE id = ANY (p_deleted)
         AND budget_version_id = p_version_id
       RETURNING id, description, category, amount_kes, sort_order
    )
    SELECT COALESCE(
      jsonb_agg(jsonb_build_object(
        'id',          del.id,
        'description', del.description,
        'category',    del.category,
        'amount_kes',  del.amount_kes,
        'sort_order',  del.sort_order
      )),
      '[]'::jsonb
    )
      INTO v_deleted_rows
      FROM del;
  ELSE
    v_deleted_rows := '[]'::jsonb;
  END IF;

  IF v_added_count > 0 THEN
    WITH src AS (
      SELECT
        (row_number() OVER ())::int - 1 AS idx,
        a
      FROM jsonb_array_elements(p_added) AS t(a)
    ),
    ins AS (
      INSERT INTO public.budget_items (
        budget_version_id,
        description,
        category,
        amount_kes,
        unit_cost_kes,
        quantity,
        sort_order,
        idempotency_key
      )
      SELECT
        p_version_id,
        (s.a->>'description'),
        NULLIF(s.a->>'category', ''),
        COALESCE((s.a->>'amount_kes')::NUMERIC(16,2), 0),
        COALESCE((s.a->>'amount_kes')::NUMERIC(16,2), 0),
        1,
        COALESCE((s.a->>'sort_order')::INT, s.idx),
        p_idempotency_key
      FROM src s
      RETURNING id, description, category, amount_kes, sort_order
    )
    SELECT COALESCE(
      jsonb_agg(jsonb_build_object(
        'id',          ins.id,
        'description', ins.description,
        'category',    ins.category,
        'amount_kes',  ins.amount_kes,
        'sort_order',  ins.sort_order
      )),
      '[]'::jsonb
    )
      INTO v_added_rows
      FROM ins;
  ELSE
    v_added_rows := '[]'::jsonb;
  END IF;

  IF v_edited_count > 0 THEN
    WITH patches AS (
      SELECT
        (e->>'id')::UUID                       AS id,
        e ? 'description'                       AS has_description,
        e ? 'category'                          AS has_category,
        e ? 'amount_kes'                        AS has_amount_kes,
        e ? 'sort_order'                        AS has_sort_order,
        NULLIF(e->>'description', '')           AS new_description,
        NULLIF(e->>'category', '')              AS new_category,
        (e->>'amount_kes')::NUMERIC(16,2)       AS new_amount_kes,
        (e->>'sort_order')::INT                 AS new_sort_order
      FROM jsonb_array_elements(p_edited) e
    ),
    upd AS (
      UPDATE public.budget_items bi
         SET description   = CASE WHEN p.has_description THEN p.new_description ELSE bi.description   END,
             category      = CASE WHEN p.has_category    THEN p.new_category    ELSE bi.category      END,
             amount_kes    = CASE WHEN p.has_amount_kes  THEN p.new_amount_kes  ELSE bi.amount_kes    END,
             unit_cost_kes = CASE WHEN p.has_amount_kes  THEN p.new_amount_kes  ELSE bi.unit_cost_kes END,
             sort_order    = CASE WHEN p.has_sort_order  THEN p.new_sort_order  ELSE bi.sort_order    END
        FROM patches p
       WHERE bi.id = p.id
         AND bi.budget_version_id = p_version_id
       RETURNING bi.id, bi.description, bi.category, bi.amount_kes, bi.sort_order
    )
    SELECT COALESCE(
      jsonb_agg(jsonb_build_object(
        'id', upd.id,
        'before', (
          SELECT s FROM jsonb_array_elements(v_before_snapshot) s
           WHERE (s->>'id')::UUID = upd.id
           LIMIT 1
        ),
        'after', jsonb_build_object(
          'description', upd.description,
          'category',    upd.category,
          'amount_kes',  upd.amount_kes,
          'sort_order',  upd.sort_order
        )
      )),
      '[]'::jsonb
    )
      INTO v_edited_rows
      FROM upd;
  ELSE
    v_edited_rows := '[]'::jsonb;
  END IF;

  UPDATE public.budget_versions
     SET total_amount_kes = (
       SELECT COALESCE(SUM(amount_kes), 0)
         FROM public.budget_items
        WHERE budget_version_id = p_version_id
     )
   WHERE id = p_version_id
   RETURNING total_amount_kes INTO v_new_total;

  -- Route-compatible audit shape (Q4 resolution): old_values = NULL,
  -- full {added, edited, deleted, new_total_amount_kes, before} payload
  -- in new_values. Mirrors the route's existing audit row at
  -- src/app/api/budgets/update/route.ts:503-513 so downstream audit_logs
  -- consumers (currently a human reader) don't see a shape change.
  INSERT INTO public.audit_logs (
    user_id,
    action,
    table_name,
    record_id,
    old_values,
    new_values,
    reason
  ) VALUES (
    p_user_id,
    'budget_items_synced',
    'budget_versions',
    p_version_id,
    NULL,
    jsonb_build_object(
      'added',                v_added_rows,
      'edited',               v_edited_rows,
      'deleted',              v_deleted_rows,
      'new_total_amount_kes', v_new_total,
      'before',               v_before_snapshot
    ),
    NULL
  )
  RETURNING id INTO v_audit_id;

  RETURN jsonb_build_object(
    'ok',                TRUE,
    'idempotent_hit',    FALSE,
    'version_total_kes', v_new_total,
    'audit_log_id',      v_audit_id
  );
END;
$$;


-- ---------------------------------------------------------------------------
-- 4. No GRANT EXECUTE
-- ---------------------------------------------------------------------------
-- Intentional. Every existing SECURITY DEFINER RPC in this repo ships
-- without an explicit GRANT EXECUTE (see fn_budget_resubmit and family in
-- 00042; fn_payments_recompute_invoice in 00059). Postgres defaults
-- EXECUTE on a new function in `public` to PUBLIC, which covers Supabase's
-- service_role (the role used by /api/budgets/update via the admin
-- client). Adding an explicit grant here would deviate from the
-- established pattern.


-- ---------------------------------------------------------------------------
-- 5. No backfill
-- ---------------------------------------------------------------------------
-- idempotency_key is nullable and brand-new on this table. Pre-existing
-- budget_items rows stay NULL by design; the partial unique index does
-- not constrain NULL values, so legacy rows are unaffected. There is
-- nothing to backfill: only rows inserted by fn_budget_items_sync carry
-- a key, and only then for the purpose of de-duping a retried sync.
